bot_token: "1142446947:AAHAbEq49jLAy2d1ByTLXBoLzLlGvqLoWR0"
admins: [213447542]
database_uri: postgresql+asyncpg://postgres:postgres@localhost:5432/sumka
redis_host: localhost
redis_port: 6379
redis_db: 0
redis_password: None
redis_prefix: bot_fsm