"""added link from user to town

Revision ID: 208d7e22c0f1
Revises: 118ab04f6945
Create Date: 2022-03-19 20:54:28.233119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208d7e22c0f1'
down_revision = '118ab04f6945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('town_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_town_id'), 'user', 'town', ['town_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_town_id'), 'user', type_='foreignkey')
    op.drop_column('user', 'town_id')
    # ### end Alembic commands ###
