"""as

Revision ID: 23da0ac8137d
Revises: 5142a75a0e01
Create Date: 2022-04-01 22:16:57.815728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23da0ac8137d'
down_revision = '5142a75a0e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'rating')
    # ### end Alembic commands ###
