"""вкdrop useless fields

Revision ID: 43fd5a959fed
Revises: 208d7e22c0f1
Create Date: 2022-03-19 21:52:15.469412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fd5a959fed'
down_revision = '208d7e22c0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
