"""a

Revision ID: 5142a75a0e01
Revises: 5f529c1659b2
Create Date: 2022-03-27 17:26:35.289796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5142a75a0e01'
down_revision = '5f529c1659b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_category_parent_category_id'), 'category', 'category', ['parent_category_id'], ['id'])
    op.drop_column('category', 'is_global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_category_parent_category_id'), 'category', type_='foreignkey')
    op.drop_column('category', 'parent_category_id')
    # ### end Alembic commands ###
