"""1

Revision ID: 5cf3a1cab525
Revises: 38d074bd6826
Create Date: 2022-04-06 15:43:54.052952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf3a1cab525'
down_revision = '38d074bd6826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'rating',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.alter_column('town', 'rating',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('town', 'rating',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('category', 'rating',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
