"""added Category

Revision ID: 5f529c1659b2
Revises: 43fd5a959fed
Create Date: 2022-03-21 12:49:19.517797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f529c1659b2'
down_revision = '43fd5a959fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('town_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], name=op.f('fk_category_town_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
