"""add rating to town list

Revision ID: 6fa0b3dd68d1
Revises: 23da0ac8137d
Create Date: 2022-04-02 16:28:51.352915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa0b3dd68d1'
down_revision = '23da0ac8137d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('town', 'rating')
    # ### end Alembic commands ###
